version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_retta
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
